# Element wise Tensor operators

In [1]:
import torch
import numpy as np
# an element wise operation operates on corresponding elements
# Jeremy Howard, Fast AI

In [2]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)


t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype=torch.float32)


# corresponding elements = 1,9 or 2,8 or 4,6


In [3]:
t1[0][0]

tensor(1.)

In [4]:
t2[0][0]

tensor(9.)

### t1[0][0], t2[0][0]  are corresponding elements
***

In [5]:
# same shape required in order to perform an element wise operation


In [6]:
t1 + t2 #corr elements are added together

tensor([[10., 10.],
        [10., 10.]])

In [7]:
t1 - t2

tensor([[-8., -6.],
        [-4., -2.]])

In [8]:
t1 * t2

tensor([[ 9., 16.],
        [21., 24.]])

In [9]:
t1 / t2

tensor([[0.1111, 0.2500],
        [0.4286, 0.6667]])

In [10]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)


print(t1.add(2)) # adds 2 to every element in the tensor

print(t1.sub(2))

print(t1.mul(2))

print(t1.div(2))

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


### Broadcasting tensors

***

In [11]:
t1 + 2     # 2 is added to every element of the tensor

tensor([[3., 4.],
        [5., 6.]])

In [12]:
# interesting case
t1 = torch.tensor([
    [1,1],
    [1,1]
], dtype=torch.float32)


t2 = torch.tensor([2,4], dtype = torch.float32)



In [13]:
t1 + t2 #t1, t2 are of different shapes
# low rank tensor is transformed via broadcasting 

tensor([[3., 5.],
        [3., 5.]])

In [14]:
# broadcast transformation, using Numpy broadcast_to function

np.broadcast_to(t2.numpy(), t1.shape)

# learn more about broadcasting

array([[2., 4.],
       [2., 4.]], dtype=float32)

In [26]:
# comparision operation

t = torch.tensor([
    [0,5,7],
    [6,0,7],
    [0,8,0]
], dtype = torch.float32)



In [33]:
t.eq(0)

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [34]:
t.ge(0) #greater equal to

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [39]:
t.gt(0) #greater than

tensor([[False,  True,  True],
        [ True, False,  True],
        [False,  True, False]])

In [40]:
t.le(0)

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [44]:
t.lt(0)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [45]:
# functions, they are applied to each element of the tensor

t.abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [46]:
t.sqrt()

tensor([[0.0000, 2.2361, 2.6458],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [47]:
t.neg()

tensor([[-0., -5., -7.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

In [48]:
t.neg().abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])