In [1]:
import torch
import numpy as np
#In the general case, an array of numbers arranged on a regular grid with a variable number of axes is known as a tensor.
#tensors are fancy lists

In [2]:
mu = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

#simple 3,3 array

In [3]:
t = torch.tensor(mu)
t
#list converted to tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
type(t)

torch.Tensor

In [5]:
t.shape

torch.Size([3, 3])

In [6]:
#rank = len(shape)

In [7]:
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [8]:
t.reshape(1,9).shape

torch.Size([1, 9])

In [ ]:
#CNN tensor shapes
[B , C , H , W]



B = Batch Size

C = Color Size (1 = greyscale, 3 = RGB)

H = Height

W = Width

In [9]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.int64
cpu
torch.strided


In [10]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [11]:
data = np.array([2,3,4,5])
type(data)

numpy.ndarray

In [12]:
torch.Tensor(data)

tensor([2., 3., 4., 5.])

In [13]:
torch.tensor(data)

tensor([2, 3, 4, 5])

In [14]:
torch.as_tensor(data)

tensor([2, 3, 4, 5])

In [15]:
torch.from_numpy(data)

tensor([2, 3, 4, 5])

In [16]:
#eye func = identity matrix
torch.eye(3) # 3x3 id matrix

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [17]:
#all zeroes 
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [18]:
#all ones
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
#random
torch.rand(3,3)
#part 9 deeplizard pytorch

tensor([[0.4717, 0.5692, 0.8824],
        [0.9448, 0.8975, 0.6219],
        [0.8752, 0.0358, 0.5107]])

In [20]:
#on the money stuff below
t1=torch.Tensor(data)     # Class constructor
t2=torch.tensor(data)     #lower case t, Factory function
t3=torch.as_tensor(data)  #factory function
t4=torch.from_numpy(data) # factory function

#factory function choose a dtype based on the incoming data


print(t1.dtype) #constructor uses global default dtype value
print(t2.dtype) #these bois infer the data type
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int64
torch.int64
torch.int64


In [21]:
torch.get_default_dtype() #same as (t1.dtype)

torch.float32

In [22]:
#factory function choose a dtype based on the incoming data, see below
d=torch.tensor(np.array([1.,2.,3.,4.,6.9])) #factory func, float input
d.dtype

#valid for other factory functions as well


torch.float64

In [23]:
#checking for another factory function
f = torch.as_tensor(np.array([1.,3.,6.9]))
f.dtype

torch.float64

In [34]:
#Memory Allocation thing
#leave the tensors alone, modify the numpy array

data = np.array([2,3,4,5])
t1=torch.Tensor(data)     
t2=torch.tensor(data)     
t3=torch.as_tensor(data)  
t4=torch.from_numpy(data) 


In [26]:
data[0] = 0
data[1] = 0
data[2] = 0
data[3] = 0
#array modified


In [32]:
print(t1)  # create an additional copy of the input data in memory
print(t2)
#old news

tensor([2., 3., 4., 5.])
tensor([2, 3, 4, 5])


In [37]:
print(t3)  # share data in memory with the numpy array
print(t4)
#hmm, zeroes in this case

tensor([2, 3, 4, 5])
tensor([2, 3, 4, 5])



# __Memory allocation__

Share Data (More efficient)
1. torch.as_tensor() 
2. torch.from_numpy()


Copy Data
1. torch.tensor() *
2. torch.Tensor()


_best option = torch.tensor()_


_for performance = torch.as_tensor()_

why?

as_tensor() accepts any array like python data structure

***


***
# Tensor Operation Types

1. Reshaping operations
2. Element-wise operations
3. Reduction operations
4. Access operations

In [44]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]   
], dtype = torch.float32)


In [46]:
t.size()

torch.Size([3, 3])

In [47]:
t.shape

torch.Size([3, 3])

In [48]:
rank = len(t.shape)
rank


2

In [53]:
#product(shape) = no. of components
print(torch.tensor(t.shape).prod())
#contains 9 components

#numel() function does the same thing
print(t.numel())

tensor(9)
9


In [55]:
t.reshape(1,9)

tensor([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [56]:
t.reshape(3,3)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [57]:
t.reshape(9,1)

tensor([[1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [3],
        [3],
        [3]])

In [ ]:
# Squeezing and Unsqueezing

#Squeezing : removes all axes havine length = 1 , removes a [] layer kinda

#Unsqueezing : adds an dimension with a length of one, adds  a [] layer

In [65]:
#Flatening a tensor

def flatten(t):
    t = t.reshape(1,-1)
    # -1 : pytorch will figure it out
    # if t has 12 elements, -1 = 12, pytorch figures this out
    t = t.squeeze() #removes a [ ] layer
    return(t)

In [66]:
flatten(t)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [72]:
# Concatenate (basic)
t1 = torch.tensor([
    [1,1,1],
    [1,1,1]
])

t2 = torch.tensor([
    [2,2,2],
    [2,2,2]
])

torch.cat((t1,t2), dim =0)

tensor([[1, 1, 1],
        [1, 1, 1],
        [2, 2, 2],
        [2, 2, 2]])