# Reduction Operations

In [ ]:
# Reduction operation reduces the number of elements contained within the tensor



In [3]:
import torch
import numpy as np

In [4]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)

In [7]:
t.sum()

tensor(8.)

In [8]:
t.numel()

9

In [9]:
t.sum().numel()

1

In [10]:
t.sum().numel() < t.numel()

True

In [11]:
t.mean()

tensor(0.8889)

In [12]:
t.std()

tensor(1.1667)

In [16]:
# els along first axis are arrays, second = numbers
t1 = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype = torch.float32)

In [17]:
t1.sum(dim=0)

tensor([6., 6., 6., 6.])

In [21]:
# under the hood
t1[0] + t1[1] + t1[2]

tensor([6., 6., 6., 6.])

In [22]:
t1.sum(dim=1)

tensor([ 4.,  8., 12.])

In [25]:
# under the hood

t1[0].sum(),t1[1].sum(),t1[2].sum()

(tensor(4.), tensor(8.), tensor(12.))

***
# Argmax

argmax() tells us the index location of the maximum value inside a tensor

In [26]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
], dtype=Torch.float32)

In [27]:
t.max()

tensor(5)

In [35]:
t.argmax() 
# max el is at index 11, wut, look at tthe flattened output below
# argmax() returns the location from the flattened tensor

tensor(11)

In [41]:
t.flatten() # 5 is at 11th index

tensor([1, 0, 0, 2, 0, 3, 3, 0, 4, 0, 0, 5])

In [55]:
# working with specific axes
# dim=0 : vertical scanner
# dim=1 : horizintal line scanner


t.max(dim=0) # vertical line scanner
t.max(dim=1) # inside each array
#argmax == second return tensor

torch.return_types.max(
values=tensor([2, 3, 5]),
indices=tensor([3, 2, 3]))

In [56]:
t.argmax(dim=0) # vertical line scanner
# 4 is at index 2 of first  axis
# 3,3 at index 1 of first axis
# 5 at index 2 of first axis


tensor([2, 1, 1, 2])

***
# Access

In [60]:
t =  torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype = torch.float32)

In [62]:
t.mean()

tensor(5.)

In [65]:
t.mean().item()

5.0

In [66]:
t.mean(dim=0).tolist() 

[4.0, 5.0, 6.0]

In [ ]:
t.mean(dim=0).